version: '1'
services:  
  aeps_database:
    build:
      context: ./aeps_database_mysql/
      dockerfile: Dockerfile
    restart: always        
    ports:
      - "3306:3306"
    env_file:
     - ./aeps_database_mysql/.env

  aeps_web_management:
    build:
      context: ./aeps_web_management/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - aeps_database
    env_file:
     - ./aeps_web_management/.env
    ports:
      - "8000:80"
    volumes:

#  superset:
#    build:
#      context: ./aeps_visualization_superset/
#      dockerfile: Dockerfile
#    restart: always
#    depends_on:
#      - mysql
#    environment:
#      MAPBOX_API_KEY: ""
#    ports:
#      - "8088:8088"
#    volumes:
      
volumes:
  mysql:
#    - ./mysql/:/var/lib/mysql
#  redis:
#    - ./superset/:/etc/superset/
